In [1]:
# Câu 1: Câu nào sau đây là đúng để tạo mảng 1 chiều từ 0 đến 9

import numpy as np
arr1_1 = np. arange (0, 10, 1)
arr1_2 = np. arange (1, 10, 1)
arr1_3 = np. arange (0, 9, 1)
arr1_4 = np. arange (1, 11, 1)

print('a: ', arr1_1)
print('b: ', arr1_2)
print('c: ', arr1_3)
print('d: ', arr1_4)

a:  [0 1 2 3 4 5 6 7 8 9]
b:  [1 2 3 4 5 6 7 8 9]
c:  [0 1 2 3 4 5 6 7 8]
d:  [ 1  2  3  4  5  6  7  8  9 10]


In [2]:
# Câu 2 : Cách tạo một mảng boolean 3x3 với tất cả giá trị là True

arr2_1 = np. ones ((3 ,3) ) > 0
arr2_2 = np. ones ((3 ,3) , dtype = bool )
arr2_3 = np. full ((3 ,3) , fill_value =True , dtype = bool )

print('a: \n', arr2_1)
print('b: \n', arr2_2)
print('c: \n', arr2_3)

a: 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
b: 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
c: 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
# Câu 3:

arr3 = np.arange(0, 10)
print(arr[arr3 % 2 == 1])

[1 3 5 7 9]


In [8]:
# Câu 4:

arr4 = np.arange(0, 10)
arr4[arr4 % 2 == 1] = -1 # Thay thế những số không chia hết cho 2 là -1
print(arr4)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [9]:
# Câu 5:

arr5 = np.arange(10)
arr_2d5 = arr5.reshape(2, -1) # Định hình lại thành mảng 2 chiều với 2 hàng và số cột tự động tính toán
print(arr_2d5)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
# Câu 6:

arr6_1 = np.arange(10).reshape(2, -1)
arr6_2 = np.repeat(1, 10).reshape(2, -1)
c6 = np.concatenate([arr6_1, arr6_2], axis = 0)
print("Result: \n", c6)

Result: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [4]:
# Câu 7:

arr7_1 = np.arange(10).reshape(2, -1)
arr7_2 = np.repeat(1, 10).reshape(2, -1)
c7 = np.concatenate([arr7_1, arr7_2], axis =1)
print("C = ", c7)

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [5]:
# Câu 8:

arr8 = np.array([1, 2, 3])
print(np.repeat(arr8, 3))
print(np.tile(arr8, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [6]:
# Câu 9:

a9 = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a9 >= 5) & (a9 <= 10))
print("result ", a9[index])

result  [ 6  9 10]


In [7]:
# Câu 10:

def maxx(x, y):
    if x >= y:
        return x
    else:
        return y
    
a10 = np.array([5, 7, 9, 8, 6, 4, 5])
b10 = np.array([6, 3, 4, 8, 9, 7, 11])

pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a10, b10))

[ 6.  7.  9.  8.  9.  7. 11.]


In [9]:
# Câu 11:

a11 = np.array([5, 7, 9, 8, 6, 4, 5])
b11 = np.array([6, 3, 4, 8, 9, 7, 1])
print('Result: ', np.where(a11<b11, b11, a11))

Result:  [6 7 9 8 9 7 5]


In [15]:
# Câu 12: Chuyển ảnh màu sang ảnh xám dựa vào phương pháp Lightness

!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg

img = mpimg.imread("./dog.jpeg")
gray_img_01 = (np.max(img, axis=2) + np.min(img, axis=2))/ 2
gray_img_01[0, 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: d:\Vi_Tinh\GIAO_TRINH\AIO\Ho_tro_Code\AIO_VN\Module_2\Tuan_1\dog.jpeg

  0%|          | 0.00/33.7k [00:00<?, ?B/s]
100%|██████████| 33.7k/33.7k [00:00<00:00, 482kB/s]


102.5

In [16]:
# Câu 13: Chuyển ảnh màu sang ảnh xám dựa vào phương pháp Average

import matplotlib.image as mpimg
img = mpimg.imread("./dog.jpeg")
gray_img_02 = np.mean(img, axis=2)
gray_img_02[0, 0]

107.66666666666667

In [18]:
# Câu 14: Chuyển ảnh màu sang ảnh xám dựa vào phương pháp Luminosity

import matplotlib.image as mpimg
img = mpimg.imread("./dog.jpeg")
gray_img_03 = 0.21 * img[:, :, 0] + 0.72 * img[:, :, 1] + 0.07 * img[:, :, 2]
gray_img_03[0, 0]

126.22999999999999

In [21]:
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('./advertising.csv')

data = df.to_numpy()


Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: d:\Vi_Tinh\GIAO_TRINH\AIO\Ho_tro_Code\AIO_VN\Module_2\Tuan_1\advertising.csv

  0%|          | 0.00/4.06k [00:00<?, ?B/s]
100%|██████████| 4.06k/4.06k [00:00<00:00, 4.06MB/s]


In [26]:
# Câu 15:Lấy giá trị lớn nhất và chỉ mục tương ứng của nó trên cột Sales

max_sale = data[:,3].max()
max_sale_index = data[:,3].argmax()
print('Max: ', max_sale, 'Index: ', max_sale_index)

Max:  27.0 Index:  175


In [27]:
# Câu 16: Giá trị trung bình của cột TV

average_tv = data[:, df.columns.get_loc('TV')].mean()
print('Average of TV: ', average_tv)

Average of TV:  147.0425


In [32]:
# Câu 17: Số lượng bản ghi có giá trị tại cột Sales lớn hơn hoặc bằng 20

greater_20_sale_count = np.count_nonzero(data[:, 3] >= 20)
print('Count of value larger or equal 20 in Sales is: ', greater_20_sale_count)

Count of value larger or equal 20 in Sales is:  40


In [40]:
# Câu 18:Tính giá trị trung bình của cột Radio thoả mãn điều kiện giá trị tương ứng trên cột Sales lớn hơn hoặc bằng 15

greater_15_sales = data[:, 3] >= 15
greater_20_sales_average = np.mean(data[larger_15_sales, 1])
print('Average of value greater or equal 15 in Sales is: ', greater_20_sales_average)

Average of value larger or equal 15 in Sales is:  26.22293577981651


In [42]:
# Câu 19: Tính tổng các hàng của cột Sales với điều kiện giá trị Newspaper lớn hơn giá trị trung bình của cột Newspaper

news_mean_greater = data[:, 2] > np.mean(data[:, 2])
sales_sum = np.sum(data[news_mean_greater, 3])
print('Sum of sale with value of Newspaper greater than average of Newspaper: ', sales_sum)

Sum of sale with value of Newspaper greater than average of Newspaper:  1405.1


In [46]:
# Câu 20:
# Gọi giá trị trung bình của cột Sales là A
# Tạo ra mảng mới scores chứa các giá trị Good, Average và Bad sao cho: 
# nếu giá trị hiện tại > A => giá trị trong mảng mới là Good, < A thì sẽ là Bad và = A sẽ là Average. 
# Sau đó in ra kết quả scores[7:10]

A = np.mean(data[:, 3])
scores20 = np.where(data[:, 3] > A, 'Good', np.where(data[:, 3] < A, 'Bad', 'Average'))

print('Scores[7:10]: ', scores20[7:10])

Scores[7:10]:  ['Bad' 'Bad' 'Good']


In [49]:
# Câu 21:
# Gọi giá trị trên cột Sales gần nhất với giá trị trung bình cũng chính cột Sales là A. 
# Tạo ra mảng mới scores chứa các giá trị Good, Average và Bad sao cho: 
# nếu giá trị hiện tại > A => giá trị trong mảng mới là Good, < A thì sẽ là Bad và = A sẽ là Average. 
# Sau đó in ra kết quả scores[7:10]

average_sale = np.mean(data[:, 3])
A = data[np.abs(data[:, 3] - average_sale).argmin(), 3]
scores21 = np.where(data[:, 3] > A, 'Good', np.where(data[:, 3] < A, 'Bad', 'Average'))
print('Scores[7:10]: ', scores21[7:10])

Scores[7:10]:  ['Bad' 'Bad' 'Good']
